title: Shubham Goyal # your name (or website title) here
logo: "/images/SG_prof.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A Data Science professional with 3+ years of experience, specializing in Machine Learning and Sequence Modeling application. 
  
  # Previously worked in the Credit & Fraud vertical of American Express. Currently, I’m pursuing Master's in Information Systems with a focus on Machine learning and Product engineering from Northeastern University in Boston
  <br><br>
  MS Information Systems @ Northeastern University, Boston, USA
  <br><br>
  Data Scientist @ American Express
  <br><br>
  Bachelors @ IIT Kharagpur, India
  
  <a href="https://www.linkedin.com/in/goyalshubhamiitkgp/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
